### ISSUE TITLE
Phonetisaurus's python bindings only available for Python 2.7 not 3

### ISSUE THREAD

**Issue by abhiTronix** [NaomiProject/Naomi#132]
Adding to #90, 
Is Phonetisaurus's python bindings are necessary for this project as stated here: https://projectnaomi.com/docs/plugins/pocketsphinx-install.html#build-and-install-phonetisaurus

If the answer is yes, then it's only available for Python-2.7 or less specifically, not for Python-3+. Here's the comment confirming this by the repo owner: https://github.com/AdolfVonKleist/Phonetisaurus/pull/28#issuecomment-324012519

**Comment by AustinCasteel** [comment]
We do not accept issues that do not follow the issue templates, just for future reference. That being said, I am aware at the time of creation the issue template was not working properly, and I apologize.

As far as sphinx and py3... We are currently in the process of migrating over to py3, however this did come up today but nothing was said about it past the mention. I am not the one knowledgeable in the speech handling area, @aaronchantrill what do you think about this?

**Comment by aaronchantrill** [comment]
We do not currently use the phonetisaurus bindings for python, and already have Pocketsphinx working with Python3. We construct a command line argument and pass it to phonetisaurus using the subprocess module. However, since Codacy flags every use of subprocess as a potential security risk (as far as I can tell, this is due to the fact that a program could be replaced with something nefarious, but that seems like a pretty low concern overall. If someone can replace an executable on the path, it seems like they have pretty much already won control of your system) I would like to switch to using the python bindings eventually. I think when I wrote the documentation I just assumed Naomi was using the python bindings. Thanks for bringing this to our attention.
