### ISSUE TITLE
Email username and password in plaintext

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#16]

**Comment by TuxSeb** [comment]
https://docs.python.org/2/library/hashlib.html

**Comment by redragonx** [comment]
A better way would be using the Google signin apis

**Comment by TuxSeb** [comment]
finally it's not only for gmail, it form any mail adress, since i updated the emails parts to be more generic with others adress

**Comment by AustinCasteel** [comment]
Abandoning issue due to being out of date & not up to standards. Make a new issue & pull request referencing this one if this needs to be reopened.

**Comment by AustinCasteel** [comment]
Reopening, But need confirmation on if this is being worked on or not...

**Comment by redragonx** [comment]
Will give a new update comment soon.

**Comment by aaronchantrill** [comment]
Something of a fix for saving passwords not in plain text was created as part of [PR#183 Replacement for weather plugin](https://github.com/NaomiProject/Naomi/pull/183). It's still not very secure, since any Naomi plugin can request the information using a built-in function call and any interested party with a little knowledge of Python could figure out how to decrypt it from the contents of the profile.yml file directly. It would be better to require something you have or something you know in order to decrypt the password. Voice identification would be ideal "Please say 'password' to allow me to access your email" and somehow tie the decryption key to the voiceprint itself. This would make it possible for a multi-user family to all have Naomi access their email accounts individually.

**Comment by aaronchantrill** [comment]
I'm working on some higher level interfaces in naomi/app_utils.py for interacting with email/text messaging. My goal would be to make that flexible enough that plugin developers don't have to mess directly with email usernames and passwords anymore, then make it so the decrypted password and some other personal profile data will no longer be returned to any module that is outside the naomi directory (ie 3rd party plugins) so if the user wanted to write a plugin to steal email addresses and passwords out of Naomi's profile, they would have to import the cryptography.fernet module or implement that decryption themselves which should be easier to catch in a code review, or could even be added as an automatic check when installing a module from the store.

I'm not sure how to implement that, seems like stacktrace should be helpful.

**Comment by aaronchantrill** [comment]
Of course, other good ideas for allowing me to feel good about trusting Naomi with my email password would be happily considered.

**Comment by TSRBerry** [comment]
How do you feel about this: 
> You may derive a key from the hardware like pbkdf2(sha512(OSname+OSversion+CPUmodel+MACaddress)) and use that as a key to encrypt the credentials, which can be retrieved on the same machine but won't benefit an attacker if he only stole the encrypted credentials and the app's binary unless he has still access to the machine to go back and get that same value
From:
https://security.stackexchange.com/questions/79717/store-password-locally-where-how-to-pass-it-securely

Is this a good idea to make Naomi more secure? Since there is no way that an attacker could not reverse Naomi to get the encryption mechanism, I feel like attaching things to the Hardware could be a good idea.

**Comment by aaronchantrill** [comment]
@jeliebig As I understand what you are saying, it means using some bits of information from the computer itself as part of a salt. So the salt that you pass to your algorithm is a hash of OSName + MAC Address + random salt or something. Store the random salt in the profile (or a separate file), then assemble the full salt when needed. That does sound like an excellent idea, since an attacker would have to collect all the necessary bits of information from the computer in addition to the profile, which should make it easier to see if someone is trying to do something nefarious.

The downside is that the more bits of information you gather from the system, the more likely Naomi is to "forget" your password because you replaced your network card (or changed your MAC address) or upgraded your OS, but as long as this doesn't happen too often (like every time the kernel changes versions), it should be okay. Also, since we are specifically targeting Raspbian Stretch and Buster right now, I'm not sure the OS version would be sufficiently random.

It seems like something like the NAME from /etc/os-release (I'm not sure how widespread this file is, but it exists in Raspbian, CentOS, and Arch) plus the model name from /proc/cpuinfo plus one of the link addresses from `ip link show` plus the contents of /etc/hostname might work, but I'm not finding it super easy to find strings that are standard enough to be in every version of linux and still random enough to provide a good salt. Do you have any specific suggestions on where you would like to see information gathered?

Thanks,
Aaron

**Comment by TSRBerry** [comment]
Good point with the OS version. No, I don't have specific things in mind on how to salt it correctly, but I imagine it would be fine to implement the approach from my post above and slightly modify it.
I will try to implement it and then send a PR to test. (probably takes some time for me tho)

**Comment by aaronchantrill** [comment]
@jeliebig that sounds fantastic. Thank you.

**Comment by aaronchantrill** [comment]
I have organized all of the modules that use profile.get_profile_password() into naomi/app_utils.py. These are also used during configuration by by both 'naomi/commandline.py' and 'naomi/application.py'. I'd like to limit the ability to request decrypted information from the profile to files in the naomi/ directory. I think this can be accomplished using inspect
`filename, line_number, clsname, lines, index = inspect.getframeinfo(sys._getframe(1))`

**Comment by aaronchantrill** [comment]
After discussing with @redragonx on Discord, I feel like it is time to close this issue. At this point, neither the username nor password are stored in plain text on the user's machine, so casual snoopers (which I think was the original issue) can't find your password. We have restricted access to the decryption function to a few core Naomi modules, meaning that a module can no longer request your decrypted password.We have also made it so that if someone copies your profile to another computer, it also can't be decrypted without also making a salt from your filesystem, making it somewhat more difficult and also easier to spot if a 3rd party is either collecting salt information or decrypting the values within their own plugin.

Given that the password has to be unencryptable in order to Naomi to use it, this seems like the best we can do at the moment. I'm sure there will be additional security concerns that arise as we move forward, but they should be added as their own issues, not added to this one.
