### ISSUE TITLE
weather plugin broken because EOLF of yahoo service 

### ISSUE THREAD

**Issue by sbernhard** [NaomiProject/Naomi#177]
The weather speechhandler is broken because as of https://developer.yahoo.com/weather/ the weather API is EOL.

**Comment by AustinCasteel** [comment]
We are well aware about the Yahoo EOL as well as the WeatherUnderground closure. They are being addressed in issues [#96](https://github.com/NaomiProject/Naomi/issues/96) & [#98](https://github.com/NaomiProject/Naomi/issues/98). They are in the works but only having around 1-4 active developers at any given time things have to be prioritized, so the core Naomi before plugins. That in mind it is in development, however I can not give an ETA at this time.

**Comment by G10DRAS** [comment]
look in to OpenWeatherMap api. Relatively easy to implement.
https://github.com/G10DRAS/JasperModules/blob/master/client/modules/OpenWeatherMap.py

**Comment by aaronchantrill** [comment]
@G10DRAS sorry, somehow I missed your suggestion. That's certainly interesting and I like the fact that it uses a real API rather than scraping data that might change format at any time. I'm not so crazy about the fact that they are require a free subscription, which they use for email marketing and tracking purposes. I'm also not sure what the "open" in OpenWeatherMap refers to. We are working towards getting to the point of being able to more easily accept third-party plugins in the near future, and I hope you'll submit this plugin when we get there. I have always envisioned that Naomi would eventually have lots of different weather plugins for different services.

**Comment by aaronchantrill** [comment]
Resolved in [PR#183 Replacement for weather plugin](https://github.com/NaomiProject/Naomi/pull/183)
