### ISSUE TITLE
PluginError: Naomi TTI

### ISSUE THREAD

**Issue by Mechaniquake** [NaomiProject/Naomi#259]
Naomi cannot initialize "Naomi TTI" from plugins

## Description
When initializing Naomi (Milestone 3.0M16) with "python3 Naomi.py" the initial setup runs up to the e-mail notification settings and then this error occurs:

Traceback (most recent call last):
  File "Naomi.py", line 9, in <module>
    naomi.main()
  File "/home/pi/Naomi/naomi/__main__.py", line 198, in main
    save_noise=p_args.save_noise
  File "/home/pi/Naomi/naomi/application.py", line 400, in __init__
    category='tti'
  File "/home/pi/Naomi/naomi/pluginstore.py", line 331, in get_plugin
    raise PluginError("Plugin '%s' not found!" % name)
naomi.pluginstore.PluginError: Plugin 'Naomi TTI' not found!

## Expected Behavior
That the program is able to locate the plugin in ~/Naomi/plugins

## Possible Fix
Tried editing the profile.yml to point to the plugin_directory:-
"plugin_directory : ~/Naomi/plugins"

 Inspected any relevant issues in the github page and any updates to files that might break the code.

- Installed Naomi with listed option 2 (set up with a local copy of python)
audio engine: pyaudio
STT: sphinx
TTS: pico-tts
passive listening off
allowed print transcript

## Context
To have Naomi work on my system. This error is slightly confusing as all the previous settings also seem to be located in the ~/Naomi/plugins folder, so I'm wondering if there has been an edit to the naomi_tti.py recently or something else like a renaming that breaks the link.

## Your Environment
* Version used: Milestone 3.0M16
* Raspberry Pi 3 Model B+
* Operating System and version: Raspbian Buster/ 2020.02.13
* Python3 Version 3.7.2

**This is my very first issue/post on GitHub since joining.

**Comment by aaronchantrill** [comment]
Thanks for checking out our project! Sorry this isn't working.

Generally if you get an error like this, it is because there is some sort of an error when a plugin is being loaded in. You should not have to set "plugin_directory".

Naomi_TTI is pure python, so the only reason I can think of why it might be crashing is because of a missing python module, and that is usually pretty straightforward to fix.

If you can, please run Naomi like this:
```
[Naomi]$ ./Naomi --debug |& tee ~/naomi.log
```
then search for "naomi_tti" in the resulting log file. You should find something like this:
```
WARNING:naomi.pluginstore:Plugin at '/home/pi/Naomi/plugins/tti/naomi_tti' skipped! (Reason: No module named 'jiwer')
Traceback (most recent call last):
  File "/home/pi/Naomi/naomi/pluginstore.py", line 253, in detect_plugins
    plugin_info = self.parse_plugin(root)
  File "/home/pi/Naomi/naomi/pluginstore.py", line 310, in parse_plugin
    self._categories_map.values())
  File "/home/pi/Naomi/naomi/pluginstore.py", line 100, in parse_plugin_class
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/Naomi/plugins/tti/naomi_tti/__init__.py", line 2, in <module>
    from .naomi_tti import NaomiTTIPlugin
  File "/home/pi/Naomi/plugins/tti/naomi_tti/naomi_tti.py", line 5, in <module>
    from jiwer import wer
ModuleNotFoundError: No module named 'jiwer'
```
If you do, please post the entire error message with the traceback. Otherwise, please let me know and I'll try to figure out what the next step is.

**Comment by aaronchantrill** [comment]
If you installed Naomi with option 2, that means that pip would have installed the required libraries to the custom version of python, so rather than `$ python3 naomi.py` you would have to either run `$ ./Naomi` which is a shell script that should start the appropriate python, or you have to find that python version and run it (`$ ~/.config/naomi/local/bin/python Naomi.py`)

Usually if you are running the wrong python, you will hit a 'missing package pyyaml' error before getting down to naomi_tti, but I wanted to mention it in case.

**Comment by Mechaniquake** [comment]
It did seem like there was a conflict between the naomi locally installed python3.5 and my current python3.7. I went through the debug log (which occurred as you described) and installed missing py packages like jiwer. 
I ran Naomi as ./Naomi and got an import error: Pocketsphinx not installed
(I then opted to reinstall and run Naomi setup under option 1, which caused less issues but the same error occured). 
The new log file shows that it's identifying the TTI plugin, which was my first problem, and all new cases in the log file seem to show an inability to import dependencies of "numpy"

- uninstalled and reinstalled latest numpy version in site packages and reinstalled pandas as well.
- This error came up when installing mpd:
pip3 install pympd
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pympd
  Using cached https://files.pythonhosted.org/packages/7d/9b/d22e654f6fb6ae38ccb6517e734db94b5fb502fbef64b9be5d5d358efa47/pympd-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o4a5h7i8/pympd/setup.py", line 3, in <module>
        from Pyrex.Distutils import build_ext
    ModuleNotFoundError: No module named 'Pyrex'

Accepting the long process of reinstalling openfst, I may just end up installing Naobian on another sd card, but not before trying everything else.

[naomi.txt](https://github.com/NaomiProject/Naomi/files/4490364/naomi.txt)
[naomi2nd.txt](https://github.com/NaomiProject/Naomi/files/4490366/naomi2nd.txt)

**Comment by Mechaniquake** [comment]
> This error came up when installing mpd:
pip3 install pympd
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pympd
Using cached https://files.pythonhosted.org/packages/7d/9b/d22e654f6fb6ae38ccb6517e734db94b5fb502fbef64b9be5d5d358efa47/pympd-1.2.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-o4a5h7i8/pympd/setup.py", line 3, in
from Pyrex.Distutils import build_ext
ModuleNotFoundError: No module named 'Pyrex'

solved with proper command: pip3 install python-mpd

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting python-mpd
  Downloading https://www.piwheels.org/simple/python-mpd/python_mpd-0.3.0-py3-none-any.whl
Installing collected packages: python-mpd
Successfully installed python-mpd-0.3.0

**Comment by aaronchantrill** [comment]
I think you'll have better luck with `pip3 install python-mpd2`, we switched to python-mpd2 a while back because there was a bit of python2 code in python-mpd that would not run on python3.

There is a requirements file that should be used for installing the python requirements as `pip3 install --user -r python_requirements.txt` which should save you some trouble tracking down the correct plugins.

You should be able to fix the missing pocketsphinx python module by switching to the Naomi virtual environment and installing the python-pocketsphinx pypi module:
```
$ workon Naomi
(Naomi)$ pip3 install pocketsphinx
```
You should be able to install numpy the same way: `(Naomi)$ pip3 install numpy`
Thank you, and thanks for sticking with it. Getting real data about installation issues is a huge help to us right now.

**Comment by Mechaniquake** [comment]
I'd like to close this issue. 
Option 2 is unlikely to work/ difficult to set up with clashing Python versions and updates happening at different times.

Option 1 with the virtual environment worked well. I want to spend time improving the phonetic library to recognize words and my accent. I use Svox TTS  and am also looking at how to adjust the voice.

I used the Raspberry Pi3 B+ running the latest version of Rasbian and Naomi Milestone 3.0.M16

**When setting up the Pi, I'd also recommend adjusting the Swap size to reduce lag or OS freezing when, for instance, downloading OpenFst:**

$ sudo dphys-swapfile swapoff

$ sudo nano /etc/dphys-swapfile

-CONF_SWAPSIZE=1024

$ sudo dphys-swapfile setup

$ sudo dphys-swapfile swapon

$ reboot

**Option 1 did not work with the installed virtualenvwrapper version:**

remove with "sudo rm -r *virtualenvwrapper* at ~/.local/lib/python2.7/site-packages
[

$ cd

$ cd ~/.local/lib/python2.7/site-packages

(~/.local/lib/python2.7/site-packages)$ pip install --user virtualenv virtualenvwrapper==4.8.4

(~/.local/lib/python2.7/site-packages)$ cd

**Had to install pocketsphinx in the virtual environment:**

$ source ~/.virtualenv/Naomi/bin/activate

[Naomi]~$ sudo apt-get install -qq python python-dev python-pip build-essential swig git libpulse-dev libasound2-dev

[Naomi]~$ pip3 install pocketsphinx

success.

[Naomi]~$ deactivate

Finally worked. 19.04.2020 19:10

Haven't found time to tinker with it more, but I see a newer version is available with a lot of code corrected.

**Comment by aaronchantrill** [comment]
Thanks for closing the issue but please keep in touch and definitely let us know if there is any way we can be helpful.

As you mention, we did a ton of code corrections following your report and would love some feedback. It should be much easier to install now using the naomi-setup.sh script as long as you are running on a Debian Buster or Stretch derivative. The install process should work fine for Ubuntu, Mint, etc. but since there are currently still only a few people working on this project we are focused on Raspbian Buster x86 or Arm architectures and don't have the resources to constantly test the install process on other distros. We would certainly appreciate anyone who would like to work on getting this working with any other environment.

We have also updated the pre-installed Naomi image for the Raspberry Pi and created a pre-installed VirtualBox image. These could both be improved, and will be as we get more comfortable building these images, but they should get you to a working system right away without hours of compiling libraries. The Raspberry Pi image is supposed to start Naomi automatically when you power on your Pi, but has an issue where about 50% of the time you get an "illegal combination of i/o devices" error when you power it up. I have fixed that by changing the way Pulseaudio is started and adding a 10 second delay between starting pulseaudio and Naomi, but I have not copied that change to the image yet.

The VirtualBox image was built on a 64 bit virtual machine, but the client tools have trouble with running 32bit tools on a 64 bit image, so nice things like shared clipboard are not working on the current image but will be added to the next image.

As far as the setup script, everything should be working at the moment. The problem with virtualenvwrapper was solved by downgrading to an earlier version.

If you can report back on the projects you are working on, I'd love to be able to add the documentation to our website. Again, if there is any way I can be helpful, please let me know.

One of the projects I am planning to work on for the next release of Naomi is speaker identification, both so Naomi can build up databases of different users, and so that Naomi can be trained to select an acoustic model and possibly a p2g database based on the speaker. This will be using recordings of different speakers and a simple neural net to classify voices. The next level would be to match the accent if the specific speaker can't be identified, but that will require a lot more work.

I'd also love to know more about adjusting voices. It looks like MaryTTS has some tools for building a voice from labeled recordings which sounds interesting. It would also be interesting to start experimenting with adjusting the g2p dictionary to adjust accent, and with using changes in pitch and timbre to convey emotional state.
