### ISSUE TITLE
Ability to uninstall or clean-up Naomi from the installer

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#318]
## Detailed Description

This weekend my download of the pocketsphinx-python repository broke. The installer continued on happily, announcing that Naomi had been installed, but after populating the profile I got an error that the pocketsphinx module had not been installed. When I tried reinstalling, it failed again because the pocketsphinx-python directory already existed under ~/.config/naomi/sources. It would be nice to check if the ~/Naomi and ~/.config/naomi directories exist and ask if we want to clear them before proceeding. It would also be nice to give users a tool for completely removing Naomi from their systems which is also basically just removing the ~/Naomi and ~/.config/naomi directories.

## Context

I would use it to be able to do a clean reinstall of Naomi. It would also be nice to give users a tool for removing their Naomi install.

## Possible Implementation

Check if the sub() (~/.config/naomi) directory exists and offer to clear it out if it does. Just a rm -Rivf ~/.config/naomi would do it.

**Comment by AustinCasteel** [comment]
I will start working on this.

**Comment by aaronchantrill** [comment]
The installer works, but in addition to the --uninstall flag on the command line, I'd like to see the option to delete the ~/.config/naomi directory directly from within the installer if it is detected, rather than just a message asking you to run `./naomi-setup.sh --uninstall`.

Part of the reason for this is the install one-liner. If you use the one-liner to install Naomi, the naomi-setup.py program does not actually exist, so the user can't run it. It would be better to tell the user that it appears that they have already installed Naomi, and ask if they want to remove Naomi's configuration so a clean install can be done. I think we can allow them to continue without removing the configuration if they just want to upgrade the base install or switch from stable to nightly or something.

If the ~/Naomi directory already exists, the user should be given the option to keep it before being asked which edition they want. Pressing 'S' to skip the Naomi base directory download is not documented, and if someone has modifications they want to keep or that allow them to finish the install on their system, we don't want to force them to overwrite it. I also think some people will git clone Naomi directly from github and won't appreciate that the repository they just downloaded is being overwritten.

I also think we need to document that naomi-setup.py always installs the base Naomi into ~/Naomi and the configuration into ~/.config/naomi, and that it should never be run as root (otherwise Naomi gets installed under root's user account and can't be run by normal users).

**Comment by AustinCasteel** [comment]
I can retool the uninstall so that it can be called with the flag or if the script finds configs it can explain and ask you if you want to uninstall or not instead of kicking you to run the flag yourself.

I implemented the Skip version to be able to test the install scripting without overwriting any changes I have made. This isnt documented because it is only a development option and would break things if someone runs it on the oneliner.

As far as the whole re-installing or updating settings through installer, this opens up a whole slew of issues. Right now the process is very linear and is not meant to be ran more than once. If we want to have options to edit certain setting, install plugins, change versions, manually update, or alternate way to enable/disable autoupdate then I can start working on that. Along with that I can work on backups where if you run the installer/updater/whatever that effects the dir that it will move things to a timestamped backup dir so that if there are any things you would like to manually move over you can as well as wont delete anything. The reason why the directory is deleted and gotten if you are installing from source is because if you download the source but select a version that is not aligned with the repo then the source needs to be changed anyways. The only way this would be needed is if they download the dev branch and want nightly build because they are one in the same.

**Comment by aaronchantrill** [comment]
I agree, it's a matter of expectations. I have had the experience of hitting S accidentally when installing from the one-liner. That's why it makes sense to me to offer it as a separate option only if the directory exists. People installing from the oneliner would never see the question, and someone who selects to keep the existing directory would not get to choose an edition and would not get automatic updates.

**Comment by aaronchantrill** [comment]
[If ~/.config/naomi is detected]

It appears that you have installed Naomi before. If there were issues with your previous install, we recommend clearing Naomi's configuration. This includes the configuration profile, compiled dependencies, recordings, ai models, plugins installed from the Naomi Plugin Exchange, and anything that makes your Naomi unique. Would you like to clear Naomi's configuration?
Yes - rm -Rf ~/.config/naomi
No - just continue
...
[If ~/Naomi is detected ]
It appears that you have previously downloaded Naomi into the ~/Naomi directory. You can keep this version, but if you do, you will not receive automatic updates and will have to pull updates manually using Git. Would you like to keep the existing install or continue and select an edition to install?
Keep - skip the edition selection
Continue - select an edition

**Comment by AustinCasteel** [comment]
Fixed with PR https://github.com/NaomiProject/Naomi/pull/324
