### ISSUE TITLE
[Feature-Request] - Make plugins selectable

### ISSUE THREAD

**Issue by andweber** [NaomiProject/Naomi#32]
as an enhancement or idea:

Let the user choose which plugins he wants to be loaded and which not.

**Comment by chrobione** [comment]
Sounds like a great idea, need to make sure the gui makes use of it.

**Comment by aaronchantrill** [comment]
I would like to expand on what @sbernhard did by making it so that it also will check for a Yes/No/True/False after the name of the plugin to determine whether the plugin should be loaded or not. If there is nothing after the name of the plugin, then for compatibility it will load.

This way we can add some code to the plugins search which checks to see if the plugin is listed in the speechhandler section, and automatically add it if not. This should make it fairly easy for the user to turn on and off plugins.

**Comment by aaronchantrill** [comment]
When loading a plugin for the first time, it is added to profile.yml as
```
plugins:
    category:
        plugin: Enabled
```
This makes it very easy to disable specific plugins if you need to.

This change was added in [#199 Naomi Plugin Repository](https://github.com/NaomiProject/Naomi/pull/199)
