### ISSUE TITLE
[Feature-Request] - Re-adding notification plugin functionality 

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#47]
The notification plugins mode that was implemented in the 1.0 don't seem to be implemented in 2.0.

The interaction here would be passive: Naomi will do some silent monitoring of some information stream (e.g., checking Twitter or email) and tell you when there is something important to report, such as a friend's birthday you don't want to miss or an appointment in the day.

It would be cool to add a sound when it's going to tell you something (one like when you trigger Naomi , to avoid surprises).

**Comment by aaronchantrill** [comment]
I had made some changes to Brain and removed the "from notifier import Notifier" because it seemed vestigial. I see what it is doing now and have restored the comments.

It is basically just setting up a job that runs every 30 seconds and loops through an array containing a list of methods and/or functions which check for and handle incoming messages. As currently written, all it does is announce that a notification has arrived and who from.

I'm thinking about how this could be used by different plugins. I imagine this would work about the same as the processing for the list of speechhandler plugins, where each incoming message is matched to a particular handler using an intent parser, which then handles the message and instead of say-ing the results, it responds to whatever address sent the request. So, for instance, you could send a text or email to your Naomi asking for the current time, and get a response back containing the current time.

There are some special considerations here. Emails are split into distinct "from", "subject" and "body" parts. If I send a text to Naomi asking for the time, I get an email containing "Naomi, what's the time" as both subject and body. I think what makes sense is to add the subject as the first line of the body, and if the body begins with the subject, then just throw it away.

That way this message:
```
to: Naomi
subject: Naomi, what time is it?
Naomi, what time is it?
```
would appear to Naomi to be identical to the same message sent without a body, and
```
to: Naomi
subject: Naomi, what time is it
in Hawaii, Auckland, and Rome?
```
would be handled with the body adding to the subject.

I guess the whole message, subject and body, would be passed to the intent handler.

Now, you could set up Naomi with its own email account, in which case it would try to handle every request coming in, or to share your email account, in which case it would look for the wake word. I'm not sure about an exchange like:
```
from: you
to: you
subject: Naomi, what time is it?
Naomi, what time is it?
```
```
from: you
to: you
subject: re: Naomi, what time is it?
It is 6:11pm right now
```
```from: you
to: you
subject: re: re: Naomi, what time is it?
It is 6:12pm right now
```
etc. since Naomi would keep seeing its wake word in the subject and attempting to respond, and having Naomi respond without citing the original message in some way seems like it might be confusing. Seems like it would need some kind of echo cancellation, where it could recognize messages that it sent itself and disregard them, or at least strip the wake word out of the response. This could be done by inserting a special signature, but that signature would likely then be included in a response from the user (if the exchange is by email).

Which then brings us to the question of knock-knock jokes. Some Naomi actions contain scripts that require a response in order to trigger the next part. Consider the following:
```
You: Naomi, tell me a joke
Naomi: Knock, knock
You: Who's there
Naomi: Boo
You: Boo, who?
Naomi: Don't cry, it's only a knock knock joke
```
in current Naomi, it doesn't matter what response you give in these cases, just making any response is interpreted as playing along, and Naomi is unable to move on and complete other requests until the exchange is finished. If I send Naomi a list of items to take off my shopping list, or a request for an alarm, I don't want to get a response of "Orange you glad I didn't say banana?" However, it would be fun to play along a knock knock joke by text message, and texts are usually somewhat more accurate than the current state of STT transcription, so you could look for a reasonable response and failing that, start a new transaction and abandon the half-told joke.

Finally, you would probably need some additional security around having Naomi respond to emails, to prevent Naomi from responding to spam, for instance, especially as Naomi gets to know more about you. So you would probably have a list of safe addresses to respond to. This would probably require sending an email or text message to Naomi that would cause it to verbally request permission to respond to that address.

Anyway, that's what I'm thinking about, but that's a lot more than what is currently there, which is just the ability to monitor an email (gmail) account and tell the user when a new email has arrived. That could be extended to twitter, to follow particular twitter users or hashtags, or other feeds like RSS, facebook notifications, etc. 

Interesting stuff. I'm still thinking about how to put it together. These might be two different ideas, monitoring streams and processing requests arriving via a monitored stream. I did some work on app_utils a while back creating the tools for reading and sending emails without having to have direct access to the user's email address, password etc. that I think could work well here. I don't think I ever got to the point of submitting those, so I might revisit them with this project in mind.
