### ISSUE TITLE
Other mail adress support

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#57]
Support others email adress in the mail plugin 

files to change: 
* [notifier.py]( https://github.com/NaomiProject/Naomi/blob/naomi-dev/jasper/notifier.py)
* [app_utils.py](https://github.com/NaomiProject/Naom/blob/3240b05f5eb6bff6f5feec75e1aea93e894889b4/jasper/app_utils.py)
* [gmail.py plugin](https://github.com/NaomiProject/Naomi/blob/3240b05f5eb6bff6f5feec75e1aea93e894889b4/plugins/speechhandler/gmail/gmail.py)
* [News.py plugin](https://github.com/NaomiProject/Naomi/blob/3240b05f5eb6bff6f5feec75e1aea93e894889b4/plugins/speechhandler/news/news.py)
* [hackernews.py plugin](https://github.com/NaomiProject/Naomi/blob/3240b05f5eb6bff6f5feec75e1aea93e894889b4/plugins/speechhandler/hackernews/hackernews.py)

**Comment by aaronchantrill** [comment]
I've done quite a bit of work with SMTP. Looks like Python has a good general SMTP library already so this should be pretty easy. It's also something that I have been meaning to get to since i'm not a big fan of Gmail's practice of analyzing the contents of your email for advertising purposes, but I think it would be fun to receive and send email like Joaquin Phoenix in Her.

**Comment by TuxSeb** [comment]
Yeah it would be fun to send emai with Naomi, but for now i want to update the current module and core parts to make Naomi able to read any mailbox, not only Gmail

however, in a next update sending an email will come for sure😉
