### ISSUE TITLE
Rename "Jasper" into "Naomi" 

### ISSUE THREAD

**Issue by TuxSeb** [NaomiProject/Naomi#82]
Rename every "Jasper" into "Naomi" in every files, making sure everything work fine after this

**Comment by AustinCasteel** [comment]
I can knock this one out by next week if someone else doesn't want to do it before then. It only takes about an hour or two to do. (did it my self for my install)

**Comment by TuxSeb** [comment]
okay 👍  i assign you this task

**Comment by aaronchantrill** [comment]
Use of find and sed really help with things like this. I have used this to check what files need updating:
`
find . -type f -iname '*.py' -exec grep -Hi 'jasper' {} \;`

then once you have identified something

```
find . -type f -iname '*.py' -exec sed -i 's/JASPER/NAOMI/g' {} \;
find . -type f -iname '*.py' -exec sed -i 's/Jasper/Naomi/g' {} \;
find . -type f -iname '*.py' -exec sed -i 's/jasper/naomi/g' {} \;
```

should do it. I just used this to change my own jasper's name to 'Computer' a la Star Trek, just so I could have both Computer and Naomi installed at the same time and using different profile settings.

Of course, this will make it more difficult to change it to something else, since the word 'computer' appears in mic.py and __main__.py. Plus you should change the original copyright to reflect the fact that this project is a fork from Jasper.

Testing is really important after a change like this, and of course, almost every pull request that hasn't pulled this change will need manual resolution. Thanks for taking this on.

**Comment by aaronchantrill** [comment]
Of course, then you have to go through and change the names of any files or directories that contain 'jasper' to the new name also:
`find . -iname '*jasper*'`
It's easier to rename those manually than write a script for it.

**Comment by redragonx** [comment]
Closing...

**Comment by gospodima** [comment]
Hi @TuxSeb, 
As far as I can see 'Jasper' still remains as key phrase in the project, doesn't it?

**Comment by AustinCasteel** [comment]
Yes, the keyword is still Jasper. We are in the works on implementing snowboy in a later release which will allow the user to chose their own keyword, but for now Jasper remains.

**Comment by aaronchantrill** [comment]
I haven't used "jasper" as a trigger since before the Naomi project forked. The Populate.py script asks you what trigger phrase you want to use, with a default of Naomi. It's just an entry (keyword) in profile.yml. Am I misunderstanding the question?

**Comment by AustinCasteel** [comment]
After digging further in, the base Naomi will use what keyword you input during the populate process as @aaronchantrill said. The only places that still have "jasper" as a keyword are the testutils, local_mic, & batch_mic.

**Comment by aaronchantrill** [comment]
Okay, I'm pretty sure all of those can be changed with no ill effects.

**Comment by aaronchantrill** [comment]
Especially all the defaults when there is no "keyword" entry in profile.yml

**Comment by AustinCasteel** [comment]
When I made the conversion some things were changed that were not supposed to be and some things did not change even though there were supposed to. We can fix these minor things as we come across them.
